#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <math.h>

#define MIN_SHOULDER_ANGLE_RAD (MIN_SHOULDER_ANGLE * PI / 180.0)
#define MAX_SHOULDER_ANGLE_RAD (MAX_SHOULDER_ANGLE * PI / 180.0)
#define MAX_ELBOW_ANGLE_RAD (MAX_ELBOW_ANGLE * PI / 180.0)
#define LEFT_SERVO_ANGLE_OFFSET_RAD (LEFT_SERVO_ANGLE_OFFSET * PI / 180.0)
#define RIGHT_SERVO_ANGLE_OFFSET_RAD (RIGHT_SERVO_ANGLE_OFFSET * PI / 180.0)
#define SERVO_ANGLE_RANGE_RAD (SERVO_ANGLE_RANGE * PI / 180.0)

#define UPPER_ARM_LENGTH_SQUARE (sq(UPPER_ARM_LENGTH))
#define LOWER_ARM_LENGTH_SQUARE (sq(LOWER_ARM_LENGTH))
#define HOME_Y_POS sqrt(LOWER_ARM_LENGTH_SQUARE - sq(SHOULDER_SPACING / 2 + UPPER_ARM_LENGTH))

#endif